// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppendReq struct {
	Term                 int64    `protobuf:"varint,1,opt,name=Term,json=term,proto3" json:"Term,omitempty"`
	LeaderId             int32    `protobuf:"varint,2,opt,name=LeaderId,json=leaderId,proto3" json:"LeaderId,omitempty"`
	PrevLogTerm          int64    `protobuf:"varint,3,opt,name=PrevLogTerm,json=prevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	PrevLogIdx           int64    `protobuf:"varint,4,opt,name=PrevLogIdx,json=prevLogIdx,proto3" json:"PrevLogIdx,omitempty"`
	LeaderCommitLogIdx   int64    `protobuf:"varint,5,opt,name=LeaderCommitLogIdx,json=leaderCommitLogIdx,proto3" json:"LeaderCommitLogIdx,omitempty"`
	Es                   *Entries `protobuf:"bytes,6,opt,name=Es,json=es,proto3" json:"Es,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendReq) Reset()         { *m = AppendReq{} }
func (m *AppendReq) String() string { return proto.CompactTextString(m) }
func (*AppendReq) ProtoMessage()    {}
func (*AppendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *AppendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendReq.Unmarshal(m, b)
}
func (m *AppendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendReq.Marshal(b, m, deterministic)
}
func (m *AppendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendReq.Merge(m, src)
}
func (m *AppendReq) XXX_Size() int {
	return xxx_messageInfo_AppendReq.Size(m)
}
func (m *AppendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppendReq proto.InternalMessageInfo

func (m *AppendReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendReq) GetLeaderId() int32 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AppendReq) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendReq) GetPrevLogIdx() int64 {
	if m != nil {
		return m.PrevLogIdx
	}
	return 0
}

func (m *AppendReq) GetLeaderCommitLogIdx() int64 {
	if m != nil {
		return m.LeaderCommitLogIdx
	}
	return 0
}

func (m *AppendReq) GetEs() *Entries {
	if m != nil {
		return m.Es
	}
	return nil
}

type AppendRsp struct {
	Term                 int64    `protobuf:"varint,1,opt,name=Term,json=term,proto3" json:"Term,omitempty"`
	RetCode              int32    `protobuf:"varint,2,opt,name=RetCode,json=retCode,proto3" json:"RetCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendRsp) Reset()         { *m = AppendRsp{} }
func (m *AppendRsp) String() string { return proto.CompactTextString(m) }
func (*AppendRsp) ProtoMessage()    {}
func (*AppendRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *AppendRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendRsp.Unmarshal(m, b)
}
func (m *AppendRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendRsp.Marshal(b, m, deterministic)
}
func (m *AppendRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendRsp.Merge(m, src)
}
func (m *AppendRsp) XXX_Size() int {
	return xxx_messageInfo_AppendRsp.Size(m)
}
func (m *AppendRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AppendRsp proto.InternalMessageInfo

func (m *AppendRsp) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendRsp) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

type VoteReq struct {
	Term                 int64    `protobuf:"varint,1,opt,name=Term,json=term,proto3" json:"Term,omitempty"`
	CandiId              int32    `protobuf:"varint,2,opt,name=CandiId,json=candiId,proto3" json:"CandiId,omitempty"`
	LastLogIdx           int64    `protobuf:"varint,3,opt,name=LastLogIdx,json=lastLogIdx,proto3" json:"LastLogIdx,omitempty"`
	LastLogTerm          int64    `protobuf:"varint,4,opt,name=LastLogTerm,json=lastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteReq) Reset()         { *m = VoteReq{} }
func (m *VoteReq) String() string { return proto.CompactTextString(m) }
func (*VoteReq) ProtoMessage()    {}
func (*VoteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *VoteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteReq.Unmarshal(m, b)
}
func (m *VoteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteReq.Marshal(b, m, deterministic)
}
func (m *VoteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteReq.Merge(m, src)
}
func (m *VoteReq) XXX_Size() int {
	return xxx_messageInfo_VoteReq.Size(m)
}
func (m *VoteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteReq.DiscardUnknown(m)
}

var xxx_messageInfo_VoteReq proto.InternalMessageInfo

func (m *VoteReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteReq) GetCandiId() int32 {
	if m != nil {
		return m.CandiId
	}
	return 0
}

func (m *VoteReq) GetLastLogIdx() int64 {
	if m != nil {
		return m.LastLogIdx
	}
	return 0
}

func (m *VoteReq) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type VoteRsp struct {
	Term                 int64    `protobuf:"varint,1,opt,name=Term,json=term,proto3" json:"Term,omitempty"`
	VoteGranted          int32    `protobuf:"varint,2,opt,name=VoteGranted,json=voteGranted,proto3" json:"VoteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteRsp) Reset()         { *m = VoteRsp{} }
func (m *VoteRsp) String() string { return proto.CompactTextString(m) }
func (*VoteRsp) ProtoMessage()    {}
func (*VoteRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *VoteRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRsp.Unmarshal(m, b)
}
func (m *VoteRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRsp.Marshal(b, m, deterministic)
}
func (m *VoteRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRsp.Merge(m, src)
}
func (m *VoteRsp) XXX_Size() int {
	return xxx_messageInfo_VoteRsp.Size(m)
}
func (m *VoteRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRsp proto.InternalMessageInfo

func (m *VoteRsp) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteRsp) GetVoteGranted() int32 {
	if m != nil {
		return m.VoteGranted
	}
	return 0
}

func init() {
	proto.RegisterType((*AppendReq)(nil), "pb.AppendReq")
	proto.RegisterType((*AppendRsp)(nil), "pb.AppendRsp")
	proto.RegisterType((*VoteReq)(nil), "pb.VoteReq")
	proto.RegisterType((*VoteRsp)(nil), "pb.VoteRsp")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x3d, 0x6b, 0xc3, 0x30,
	0x10, 0xc5, 0x8e, 0x13, 0x27, 0x27, 0xba, 0xdc, 0x64, 0x5c, 0x28, 0xc2, 0x43, 0xc9, 0xe4, 0x21,
	0x9d, 0x3a, 0x95, 0x12, 0x42, 0x09, 0x64, 0x08, 0xa6, 0x74, 0x77, 0xaa, 0x23, 0x04, 0x6c, 0x4b,
	0x95, 0x44, 0x68, 0xff, 0x62, 0x7f, 0x55, 0xb1, 0xa4, 0xd8, 0x85, 0x36, 0xe3, 0x7b, 0xf7, 0xee,
	0xe3, 0x3d, 0x09, 0x16, 0xad, 0x39, 0x96, 0x4a, 0x4b, 0x2b, 0x31, 0x56, 0x87, 0x7c, 0xd1, 0xc8,
	0x00, 0x8b, 0xef, 0x08, 0x16, 0xcf, 0x4a, 0x51, 0x27, 0x2a, 0xfa, 0x40, 0x84, 0xe4, 0x95, 0x74,
	0x9b, 0x45, 0x3c, 0x5a, 0x4e, 0xaa, 0xc4, 0x92, 0x6e, 0x31, 0x87, 0xf9, 0x8e, 0x6a, 0x41, 0x7a,
	0x2b, 0xb2, 0x98, 0x47, 0xcb, 0x69, 0x35, 0x6f, 0x02, 0x46, 0x0e, 0x6c, 0xaf, 0xe9, 0xbc, 0x93,
	0x47, 0xd7, 0x36, 0x71, 0x6d, 0x4c, 0x8d, 0x14, 0xde, 0x01, 0x04, 0xc5, 0x56, 0x7c, 0x66, 0x89,
	0x13, 0x80, 0x1a, 0x18, 0x2c, 0x01, 0xfd, 0xf4, 0xb5, 0x6c, 0xdb, 0x93, 0x0d, 0xba, 0xa9, 0xd3,
	0x61, 0xf3, 0xa7, 0x82, 0xb7, 0x10, 0x6f, 0x4c, 0x36, 0xe3, 0xd1, 0x92, 0xad, 0x58, 0xa9, 0x0e,
	0xe5, 0xa6, 0xb3, 0xfa, 0x44, 0xa6, 0x8a, 0xc9, 0x14, 0x8f, 0x83, 0x17, 0xa3, 0xfe, 0xf5, 0x92,
	0x41, 0x5a, 0x91, 0x5d, 0x4b, 0x41, 0xc1, 0x4a, 0xaa, 0x3d, 0x2c, 0xbe, 0x20, 0x7d, 0x93, 0x96,
	0xae, 0x85, 0x90, 0x41, 0xba, 0xae, 0x3b, 0x71, 0x1a, 0x32, 0x48, 0xdf, 0x3d, 0xec, 0x0d, 0xee,
	0x6a, 0x73, 0x39, 0xdc, 0x27, 0x00, 0xcd, 0xc0, 0xf4, 0x11, 0x85, 0xba, 0x1b, 0xea, 0x13, 0x60,
	0xcd, 0x48, 0x15, 0x4f, 0x61, 0xf5, 0x95, 0x9b, 0x39, 0xb0, 0xbe, 0xfc, 0xa2, 0xeb, 0xce, 0xd2,
	0x65, 0x3d, 0x3b, 0x8f, 0xd4, 0x6a, 0x0f, 0xc9, 0x9e, 0x48, 0xe3, 0x3d, 0xcc, 0xbc, 0x7d, 0xbc,
	0xe9, 0x93, 0x19, 0x9e, 0x35, 0xff, 0x0d, 0x8d, 0x42, 0x0e, 0x49, 0x3f, 0x11, 0x5d, 0x7e, 0xc1,
	0x75, 0x3e, 0x02, 0xa3, 0x0e, 0x33, 0xf7, 0x39, 0x1e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x02,
	0x38, 0x00, 0x46, 0x38, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PeerClient is the client API for Peer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeerClient interface {
	Append(ctx context.Context, in *AppendReq, opts ...grpc.CallOption) (*AppendRsp, error)
	Vote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteRsp, error)
}

type peerClient struct {
	cc *grpc.ClientConn
}

func NewPeerClient(cc *grpc.ClientConn) PeerClient {
	return &peerClient{cc}
}

func (c *peerClient) Append(ctx context.Context, in *AppendReq, opts ...grpc.CallOption) (*AppendRsp, error) {
	out := new(AppendRsp)
	err := c.cc.Invoke(ctx, "/pb.Peer/Append", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerClient) Vote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteRsp, error) {
	out := new(VoteRsp)
	err := c.cc.Invoke(ctx, "/pb.Peer/Vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServer is the server API for Peer service.
type PeerServer interface {
	Append(context.Context, *AppendReq) (*AppendRsp, error)
	Vote(context.Context, *VoteReq) (*VoteRsp, error)
}

// UnimplementedPeerServer can be embedded to have forward compatible implementations.
type UnimplementedPeerServer struct {
}

func (*UnimplementedPeerServer) Append(ctx context.Context, req *AppendReq) (*AppendRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (*UnimplementedPeerServer) Vote(ctx context.Context, req *VoteReq) (*VoteRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}

func RegisterPeerServer(s *grpc.Server, srv PeerServer) {
	s.RegisterService(&_Peer_serviceDesc, srv)
}

func _Peer_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peer/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).Append(ctx, req.(*AppendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peer_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Peer/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).Vote(ctx, req.(*VoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Peer",
	HandlerType: (*PeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _Peer_Append_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _Peer_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
